"""empty message

Revision ID: 5fcbcabfe41c
Revises: 70458ea493d1
Create Date: 2021-09-19 21:57:02.297362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcbcabfe41c'
down_revision = '70458ea493d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=30), nullable=False),
    sa.Column('passengers', sa.String(length=30), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('vehicle_class', sa.String(length=30), nullable=True),
    sa.Column('crews', sa.String(length=30), nullable=True),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('starships')
    # ### end Alembic commands ###
