"""empty message

Revision ID: 96986685c2c5
Revises: f882290cdc98
Create Date: 2021-09-19 23:31:26.482909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96986685c2c5'
down_revision = 'f882290cdc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('passengers', sa.String(length=30), nullable=True))
    op.drop_column('vehicles', 'vehicle_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_class', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('vehicles', 'passengers')
    # ### end Alembic commands ###
